import { motion, AnimatePresence } from 'framer-motion';
import { useState, useEffect } from 'react';
import { Sparkles, X, Loader2, Plus } from 'lucide-react';
import { useTaskStore } from '../stores';
import type { Task } from '../data/mockData';

interface Props {
  task: Task;
  onClose: () => void;
}

const breakdownExamples: Record<string, string[]> = {
  default: [
    'Research and gather requirements',
    'Create initial design/mockup',
    'Implement core functionality',
    'Write tests and documentation',
    'Review and iterate on feedback',
  ],
};

export default function AIBreakdown({ task, onClose }: Props) {
  const { addTask, tasks } = useTaskStore();
  const [isGenerating, setIsGenerating] = useState(true);
  const [subtasks, setSubtasks] = useState<string[]>([]);
  const [addedIds, setAddedIds] = useState<string[]>([]);

  useEffect(() => {
    // Simulate AI generation
    const timer = setTimeout(() => {
      setSubtasks(breakdownExamples.default);
      setIsGenerating(false);
    }, 2000);
    return () => clearTimeout(timer);
  }, []);

  const addSubtask = (title: string, index: number) => {
    const newTask: Task = {
      id: `t-ai-${Date.now()}-${index}`,
      title,
      description: 'Generated by AI breakdown',
      completed: false,
      priority: task.priority,
      projectId: task.projectId,
      labels: task.labels,
      createdAt: new Date().toISOString(),
      subtasks: [],
      parentId: task.id,
      order: tasks.length + index,
      status: 'todo',
    };
    addTask(newTask);
    setAddedIds(prev => [...prev, title]);
  };

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 bg-black/60 backdrop-blur-md z-[60] flex items-center justify-center p-4"
      onClick={onClose}
    >
      <motion.div
        initial={{ opacity: 0, scale: 0.95, y: 20 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.95, y: 20 }}
        transition={{ type: 'spring', stiffness: 300, damping: 25 }}
        onClick={(e) => e.stopPropagation()}
        className="w-full max-w-md bg-[#0A0A0A] border border-white/10 rounded-2xl shadow-[0_0_60px_rgba(255,215,0,0.1)]"
      >
        <div className="p-5">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-2">
              <motion.div
                animate={{ rotate: 360 }}
                transition={{ duration: 2, repeat: Infinity, ease: 'linear' }}
              >
                <Sparkles className="w-5 h-5 text-aurum-gold" />
              </motion.div>
              <h3 className="text-lg font-semibold text-aurum-text">AI Task Breakdown</h3>
            </div>
            <button onClick={onClose} className="p-1.5 hover:bg-white/5 rounded-lg">
              <X className="w-4 h-4 text-aurum-muted" />
            </button>
          </div>

          <div className="bg-white/[0.03] border border-white/5 rounded-xl p-3 mb-4">
            <p className="text-xs text-aurum-muted mb-1">Breaking down:</p>
            <p className="text-sm text-aurum-text font-medium">{task.title}</p>
          </div>

          {isGenerating ? (
            <div className="py-8 flex flex-col items-center gap-3">
              <motion.div
                animate={{ rotate: 360 }}
                transition={{ duration: 1, repeat: Infinity, ease: 'linear' }}
              >
                <Loader2 className="w-8 h-8 text-aurum-gold" />
              </motion.div>
              <motion.p
                animate={{ opacity: [0.5, 1, 0.5] }}
                transition={{ duration: 1.5, repeat: Infinity }}
                className="text-sm text-aurum-secondary"
              >
                Analyzing task complexity...
              </motion.p>
              <div className="w-48 h-1 bg-white/5 rounded-full overflow-hidden">
                <motion.div
                  initial={{ width: '0%' }}
                  animate={{ width: '100%' }}
                  transition={{ duration: 2 }}
                  className="h-full gold-gradient rounded-full"
                />
              </div>
            </div>
          ) : (
            <div className="space-y-2">
              {subtasks.map((subtask, i) => (
                <motion.div
                  key={subtask}
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: i * 0.1 }}
                  className="flex items-center gap-2 p-2.5 rounded-lg bg-white/[0.03] border border-white/5"
                >
                  <span className="text-xs text-aurum-muted w-5">{i + 1}.</span>
                  <span className="text-sm text-aurum-text flex-1">{subtask}</span>
                  {addedIds.includes(subtask) ? (
                    <span className="text-xs text-aurum-gold">✓ Added</span>
                  ) : (
                    <motion.button
                      whileHover={{ scale: 1.1 }}
                      whileTap={{ scale: 0.9 }}
                      onClick={() => addSubtask(subtask, i)}
                      className="p-1 hover:bg-aurum-gold/10 rounded"
                    >
                      <Plus className="w-4 h-4 text-aurum-gold" />
                    </motion.button>
                  )}
                </motion.div>
              ))}
            </div>
          )}

          {!isGenerating && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.5 }}
              className="mt-4 flex justify-end gap-2"
            >
              <button
                onClick={() => subtasks.forEach((s, i) => !addedIds.includes(s) && addSubtask(s, i))}
                className="px-4 py-2 rounded-xl text-sm font-medium gold-gradient text-black"
              >
                Add All Subtasks
              </button>
            </motion.div>
          )}
        </div>
      </motion.div>
    </motion.div>
  );
}
